name: Test Suite & Performance Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          
      - name: Build application
        run: npm run build
        
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist/
          
  accessibility:
    name: Accessibility Audit
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Run accessibility tests
        run: npm run test -- tests/accessibility.spec.ts
        
  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test, accessibility]
    if: always()
    
    steps:
      - name: Test Results
        run: |
          echo "✅ Unit Tests: ${{ needs.test.result }}"
          echo "✅ Accessibility Tests: ${{ needs.accessibility.result }}"
          
          if [ "${{ needs.test.result }}" != "success" ] || [ "${{ needs.accessibility.result }}" != "success" ]; then
            echo "❌ Some tests failed"
            exit 1
          fi
          
          echo "🎉 All tests passed!"
